### ISSUE TITLE
Some questions about the run of fastspec 

### ISSUE THREAD

**Issue by JJJXXXI** [vernamlab/FastSpec#3]
I want to simply test fastspec ,but there are no data in the dir 'Fastspec/data',could you please upload a version with simple data set

**Comment by canertol** [comment]
The easiest way to run it on a simple data would be using the `/FastSpec/example` folder. You can just run `sh scan.sh` and it scans the example binary `libcrypto-lib-ex_data.o`. If you have more binaries that you want to scan, just move them into the `example` folder and add their names into line 7 in `scan.sh`.

**Comment by JJJXXXI** [comment]
> The easiest way to run it on a simple data would be using the `/FastSpec/example` folder. You can just run `sh scan.sh` and it scans the example binary `libcrypto-lib-ex_data.o`. If you have more binaries that you want to scan, just move them into the `example` folder and add their names into line 7 in `scan.sh`.
You may have misunderstood me, what I want to do is port it to a new architecture, so I need to start from scratch, if possible I would like to see a simple process from the initial assembly file to the training sequence

**Comment by canertol** [comment]
Our dataset is shared in the [dataset](https://github.com/vernamlab/FastSpec/tree/master/dataset) folder. If all you need is the assembly dataset, it should be fine. Unfortunately, the training script will not work as it is since you need to modify the paths for the dataset, config files, etc for your system.
